
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./templates:/usr/share/nginx/html/
    depends_on:
      - node

  node:
    build: node/.
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=mydatabase
    volumes:
      - ./node:/home/node/app
      - ./node/node_modules:/home/node/app/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: