

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    environment:
      - DOMAIN=${DOMAIN}
      - HOST=${HOST}
    entrypoint: /bin/sh -c "/etc/nginx/entrypoint.sh"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./sek_server_web/:/usr/share/nginx/sek_server_web/
    depends_on:
      - node

  node:
    build: node/.
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - RETURN_URL=${RETURN_URL}
      - REALM=${REALM}
      - REDIRECT_URL=${REDIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN=${DOMAIN}
      - HOST=${HOST}
    volumes:
      - ./node:/home/node/app
      - ./node/node_modules:/home/node/app/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # .env 파일에서 읽어옵니다.
      MYSQL_DATABASE: ${DB_NAME}                    # .env 파일에서 읽어옵니다.                       # .env 파일에서 읽어옵니다.
      MYSQL_PASSWORD: ${DB_PASSWORD}                # .env 파일에서 읽어옵니다.
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
